#! /bin/sh

# Start hotkey daemon
pkill sxhkd
sxhkd &

# Program launcher
ulauncher --hide-window --no-window-shadow &

# Start redshift with 2700K night-time colour temp
redshift -l 50:0 -t 6500:2700 &

# Desktop wallpaper manager
nitrogen --restore &

# Status bar
polybar &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width    0
bspc config window_gap      1
bspc config top_padding     0

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a ulauncher focus=on
bspc rule -a polybar border=off manage=off

bspc config external_rules_command "~/.config/bspwm/external_rules"

