#!/bin/sh

wid=$1
class=$2
instance=$3
consequences=$4
title=$(xtitle "$wid")

# Don't tile Steam Guard authentication window
if [ "$class" = "Steam" ] ; then
    if ["$title" = "Steam Guard - Computer Authorization Required" ] ; then
        echo "state=floating center=true follow=on"
    fi
fi

