#!/bin/sh

wid=$1
class=$2
instance=$3
consequences=$4
title=$(xtitle "$wid")

if [ "$class = "Steam" ]
then
	if ["title" = "Steam Guard - Computer Authorization Required" ]
	then
		echo "floating=on follow=on"
	fi
fi

